### PR TITLE
Simplify paths

### PR DESCRIPTION
**Pull request by lucianposton**
* Use relative paths so that symlinking the repo into ~/.vim works without writing into the repo
* Move python to pythonx to use vim's built-in PYTHONPATH instead of modifying sys.path.

### CODE REVIEW

**Comment by mechatroner** [comment]
Hi @lucianposton 
Thank you very much for your contribution!
I've tried to test your pull request, found some problems in the old code and finally commited this version:
https://github.com/mechatroner/minimal_gdb/commit/04b8d5a0019fdd048c4867a6a2d2893b74e16ab8

**Comment by lucianposton** [comment]
@mechatroner why not move the python files to ~/.vim/pythonx so vim can load the module whether vim uses py or py3 without modifying sys.path? Did you see an issue with that change in the PR?

In vim, see :help pythonx-directory

**Comment by mechatroner** [comment]
@lucianposton , Sorry I didn't notice pythonx directory change at first. BTW I didn't know about this feature, looks interesting, although the previous version was good well tested and worked.
And I followed the github instructions to merge your commit, but somehow it didn't appear in the commit history tree =( I am sorry about that, if you want I can try to roll it back and then merge again...

**Comment by mechatroner** [comment]
@lucianposton I reverted the commit and managed to merge yours =) Iittle by little I am learning git commands.  Thank you very much for your contribution!

**Pull request merged**
